### PR TITLE
Adds new extension to gem

### PR DESCRIPTION
**Pull request by biozid-0208**
I have added some new extensions which were needed for my work. So, I am creating this pull request.
Introduce new Feature:
anon: ip_v4_address # Faker::Internet.ip_v4_address
anon: domain_name # Faker::Internet.domain_name
anon: domain_suffix # Faker::Internet.domain_suffix
anon: commerce_price # Faker::Commerce.price
anon: decimal_number(l_digits) # Faker::Number.number(l_digits)
anon: number(digits) # Faker::Number.number(digits)

### CODE REVIEW

**Comment by ddrscott** [comment]
Thank you. I'll look it over this weekend.

**Comment by imfaruk** [comment]
Any update of this PR?

**Comment by ddrscott** [comment]
Thanks!

**Comment by ddrscott** [comment]
Oops. Just realized there's merge conflicts. Maybe I can fix them.

**Comment by ddrscott** [comment]
Merged. Thanks!

**Pull request merged**
